### ISSUE TITLE
Can't download lyrics

### ISSUE THREAD

**Issue by volteret4** [AsVHEn/deadbeef-lyricbar#9]
I added the value of the cookie, and lyrics show up after a search, but those from spotify are empty.
Probably I am missing something because I dont understand very much...
Could you help me?

PS: Sorry for opening a issue for this, but I didnt know how to reach you.

**Comment by AsVHEn** [comment]
You did everything allright. It was Spotify who stopped providing lyrics to free acounts. I want to add other lyric's sites, but I need time and knowledge to do it :D.

**Comment by volteret4** [comment]
Oh, many thanks for your quick answer. Thanks for your work with the plugin!!

**Comment by AsVHEn** [comment]
> Oh, many thanks for your quick answer. Thanks for your work with the plugin!!

I updated it to use LRCLIB to replace Spotify. Try it if you want.
